version: '3.8'

services:
  app:
    build: .
    container_name: clothing_factory_app
    volumes:
      - .:/app
      - ./images:/app/images
    environment:
      - DISPLAY=${DISPLAY}
      - DB_NAME=clothing_factory
      - DB_USER=postgres
      - DB_PASSWORD=Ostap_628
      - DB_HOST=db
      - DB_PORT=5433
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: clothing_factory_db
    environment:
      - POSTGRES_DB=clothing_factory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ostap_628
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
